# Generated by Django 3.2.4 on 2021-11-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_consulta_paciente'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
