# Generated by Django 3.2.9 on 2021-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_medico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
