# Generated by Django 3.2.9 on 2021-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_medico_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
            ],
            options={
                'ordering': ['horario'],
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='agenda',
            field=models.ManyToManyField(blank=True, to='medico.Agenda'),
        ),
    ]
