# Generated by Django 3.2.9 on 2021-11-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_auto_20211123_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='agenda',
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
    ]
