# Generated by Django 3.2.4 on 2021-11-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_auto_20211123_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
