# Generated by Django 3.2.4 on 2021-11-24 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0006_auto_20211123_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='formacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.especialidade'),
        ),
    ]
