# Generated by Django 3.2.4 on 2021-11-24 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consulta', '0002_alter_consulta_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
