# Generated by Django 3.2.4 on 2021-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_auto_20211124_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
